---
name: Build on Push

on:
  push:                 # On push to any branch
  workflow_dispatch:    # Allow manual trigger
  schedule:             # 5PM UTC every Monday
    - cron: '0 17 * * 1'

jobs:
  build:
    name: Build
    permissions:
      actions: read         # To read workflow actions (for CodeQL)
      contents: read        # To read repository contents
      pull-requests: write  # To write pull requests analysis results and artifacts
      security-events: write  # To upload CodeQL SARIF results
    uses: ./.github/workflows/build.yaml
    with:
      version: 0.0.0-run.${{ github.run_number }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
